runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets
  
- url: /static
  static_dir: static

- url: /.*
  script: marshproject.app

libraries:
- name: jinja2
  version: latest